function paramPlot(beta0_fit, W_beta0, b0,...
    wt_long_fit, W_wt_long,...
    wt_long, wt_short_fit, wt_short, covB_fit, stpX)


idx = 1:size(beta0_fit);

subplot(3, 1, 1)
plot(idx, beta0_fit,...
    idx, beta0_fit + sqrt(W_beta0), 'b:',...
    idx, beta0_fit - sqrt(W_beta0), 'b:',...
    idx, b0, 'r');
title('beta_0')

subplot(3, 1, 2)
plot(idx, wt_long_fit,...
    idx, wt_long_fit + sqrt(W_wt_long), 'b:',...
    idx, wt_long_fit - sqrt(W_wt_long), 'b:',...
    idx, wt_long, 'r');
title('wt_{long}')

se_wt_short = zeros(size(stpX, 1), 1);
for k = 1:size(stpX, 1)
    se_wt_short(k) = sqrt(stpX(k,:)*covB_fit*(stpX(k,:))');
end

subplot(3, 1, 3)
plot(idx, wt_short_fit,...
    idx, wt_short_fit + se_wt_short, 'b:',...
    idx, wt_short_fit - se_wt_short, 'b:',...
    idx, wt_short, 'r');
title('wt_{short}')

end