addpath(genpath('D:/GitHub/GBLM_SMOOTH/helper'));
addpath(genpath('D:/GitHub/GBLM_SMOOTH/core'));

%% set up...
clc;clear all;close all;
T = 120*60;
dt = 0.001;
Q = diag([3e-6 3e-6]);

trueParam_seq =...
    [[0 -1 -2 -3 -4]'*(0.07)...
    [0 -1 -2 -3 -4]'*(0.04)...
    [0 -1 -3 2 1]'*(0.05)...
    [0 1 2 3 4]'*(0.03)...
    [0 1 2 3 4]'*(0.06)...
    [0 0 0 0 0]'];

fileName_seq =...
    {'1_strong_depression.mat',...
    '2_depression.mat',...
    '3_depression_faciliation.mat',...
    '4_faciliation.mat',...
    '5_strong_faciliation.mat',...
    '6_noPlasticity.mat'};

saveDir_seq =...
    {'C:/Users/gaw19004/Desktop/ganchaoResearch/results/new/cases/constant/',...
    'C:/Users/gaw19004/Desktop/ganchaoResearch/results/new/cases/linear/',...
    'C:/Users/gaw19004/Desktop/ganchaoResearch/results/new/cases/jump/'};

beta0_seq = ...
    ... constant ...
    [repmat(-4, 1, T/dt)'...
    repmat(-4, 1, T/dt)'...
    repmat(-4, 1, T/dt)'...
    repmat(-4, 1, T/dt)'...
    repmat(-4, 1, T/dt)'...
    repmat(1.5, 1, T/dt)'...
    ... linear ...
    linspace(-3.5, -4.5, T/dt)'...
    linspace(-3.5, -4.5, T/dt)'...
    linspace(-3.5, -4.5, T/dt)'...
    linspace(-3.5, -4.5, T/dt)'...
    linspace(-3.5, -4.5, T/dt)'...
    linspace(2, 1, T/dt)'...
    ... jump ...
    [repmat(-3.5, 1, round(T/(dt*2))) repmat(-4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(-3.5, 1, round(T/(dt*2))) repmat(-4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(-3.5, 1, round(T/(dt*2))) repmat(-4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(-3.5, 1, round(T/(dt*2))) repmat(-4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(-3.5, 1, round(T/(dt*2))) repmat(-4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(2, 1, round(T/(dt*2))) repmat(1, 1, T/dt - round(T/(dt*2)))]'];


wt_long_seq = ...
    ... constant ...
    [repmat(5, 1, T/dt)'...
    repmat(4.5, 1, T/dt)'...
    repmat(4, 1, T/dt)'...
    repmat(3.5, 1, T/dt)'...
    repmat(3, 1, T/dt)'...
    repmat(1, 1, T/dt)'...
    ... linear ...
    linspace(4.5, 5.5, T/dt)'...
    linspace(4, 5, T/dt)'...
    linspace(3.5, 4.5, T/dt)'...
    linspace(2.5, 3.5, T/dt)'...
    linspace(2, 3, T/dt)'...
    repmat(1, 1, T/dt)'...
    ... jump ...
    [repmat(4.5, 1, round(T/(dt*2))) repmat(5.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(4, 1, round(T/(dt*2))) repmat(5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(3.5, 1, round(T/(dt*2))) repmat(4.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(2.5, 1, round(T/(dt*2))) repmat(3.5, 1, T/dt - round(T/(dt*2)))]'...
    [repmat(2, 1, round(T/(dt*2))) repmat(3, 1, T/dt - round(T/(dt*2)))]'...
    repmat(1, 1, T/dt)'];
%% run...

rng(123);
seed_seq = randi([0 50], 1, 18);

indx = 1;
for m = 1:3
   for n = 1:6
       
       disp(indx);
       beta0 = beta0_seq(:, indx);
       wt_long = wt_long_seq(:, indx);
       seed = seed_seq(indx);
       
       trueParam = trueParam_seq(:, n);
       saveDir = saveDir_seq{m};
       fileName = fileName_seq{n};
       caseDemoRun(T, beta0, wt_long, trueParam, seed, Q, saveDir, fileName);

       indx = indx + 1;
   end
end























